[package]
name = "advent-2022"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pathfinding = "4.1.1"
regex = "1.7.0"
serde_json = "1.0.91"
nom = "7.1.1"
nom-supreme = "0.8.0"
radix_fmt = "1.0.0"
